local addonTable = select(2, ...)

function addonTable.NewEditBox(data)
    local editBox = CreateFrame("EditBox", data.name, data.parent, "InputBoxTemplate")
    editBox:SetSize(data.width, data.height)
    editBox:SetAutoFocus(false)
    editBox:SetFontObject(GameFontHighlight)
    editBox:SetMultiLine(false)
    editBox:EnableMouse(true)
    editBox:SetMaxLetters(data.maxLetters)
    editBox:SetScript("OnEscapePressed", function(self) self:ClearFocus() end)
    editBox:SetScript("OnEnter", function(self)
        GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
        GameTooltip:SetText(addonTable.Locales.ADDON_TITLE, nil, nil, nil, 1, true)
        GameTooltip:AddLine(data.tooltipText, 1, 1, 1, 1, true)
        GameTooltip:Show()
    end)
    editBox:SetScript("OnLeave", function() GameTooltip:Hide() end)
    editBox.label = editBox:CreateFontString()
    editBox.label:SetFontObject(GameFontHighlight)
    editBox.label:SetText(data.label)
    editBox.label:SetPoint("BOTTOMLEFT", editBox, "TOPLEFT", 0, 3)
    return editBox
end